### ISSUE TITLE
Daily Rate issue

### ISSUE THREAD

**Issue by koolice19** [thenewboston-developers/Validator#113]
This is actually two issues.  The first is that the daily rate is not a prompt when setting up a validator.  If this is put into the initial manage.py script that would be helpful.

Due to this not being the case we are currently adding this on through the admin web interface of our server.  Once we make these changes on the web version and save it shows up on our validators, however it does not show this when looking at linked CV on the PV, or bank.  

![image (1)](https://user-images.githubusercontent.com/56820207/100573129-f9ef8900-328b-11eb-8a51-6c541f2b505d.png)
![image](https://user-images.githubusercontent.com/56820207/100573132-fb20b600-328b-11eb-8a70-57e301a9fe17.png)

**Comment by koolice19** [comment]
I also tried to work around this by running the manage.py set_primary_validator and followed the prompts (this was an attempt to try to force sync the new changes).  I checked my configurations on the web admin portal, and the value was still "1" for daily confirmation rate on my end, but not updated on the PV.

**Comment by buckyroberts** [comment]
This is partially fixed in an earlier update and the second issue will be fixed with https://github.com/thenewboston-developers/thenewboston-python/issues/52
