### ISSUE TITLE
Write a test to validate exceeding maximum balance gives 400 status

### ISSUE THREAD

**Issue by pgeorge2** [thenewboston-developers/Validator#125]
Write a test called `test_validate_maximum_invalid_balance_amount` and enter any 16 or more digit values to verify error with 400 status code. 
Current Maximum balance limit is set to `281474976710656`. If balance amount exeeced then it should throw validation error with 400 status.

**Comment by DucPhamTV** [comment]
@pgeorge2 , /accounts API seems like support listing accounts only, E.g: http://157.230.75.212/accounts. So Creating and updating account are impossible.
