### ISSUE TITLE
Create POST /primary_validator_upgrade_request endpoint

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Validator#22]
### Background information

Some useful background information, banks will always set their primary validator to the node that is the:

- most trusted
- online
- configured as a primary validator

### Overview of task

When a bank alters the trust levels of their validators, if the results indicate that there are now confirmation 
validators that are more trusted than the banks primary validator, the bank will send out a request to the confirmation 
validators requesting one of them upgrade to a primary validator. This is because the banks always would prefer that the 
most trusted validators are also the primary validator for the network.

| Validator| Trust |
| -------- | ----- |
| CV_001   | 98.21 |
| CV_002   | 93.87 |
| PV       | 86.04 |

A confirmation validator will accept the request if they themselves have the requesting bank set as their most trusted 
bank. Confirmation validators will always follow the guidance of their most trusted bank.

In order to prevent multiple confirmation validators from upgrading to primary validators at the same time (in the case that multiple CV's view that bank as their most trusted), the bank 
will send out these request one by one rather than sending out several requests to all CV's simultaneously.

Starting with the most trusted CV and continuing until their current PV is reached, the bank will send out an 
`/primary_validator_upgrade_request` where the following logic will be performed:

- if the CV does not have that bank set as their most trusted bank, the CV will respond "no" to the upgrade request and 
the bank will continue along with their next most trusted CV
- if the CV does have that bank set as their most trusted bank, the CV will respond "yes" to the upgrade request and upgrade themselves to a PV

If and when a CV responds "yes", the requesting bank will:

- break out of the loop (stop sending /primary_validator_upgrade_request)
- wait for that CV to upgrade themselves to a PV
- switch to their new PV

### Technical details

The CV's response of "yes" and "no" will be a response with HTTP status of `HTTP_200_OK` for yes and `HTTP_400_BAD_REQUEST` for no. This will simplify the response handling of the bank due to the fact that any error (whether it be a 400 HTTP response or the CV being offline) will result in the bank moving on to the next CV in their list.

**Comment by MrIceman** [comment]
can I work on this?
