### ISSUE TITLE
While Editing nickname duplicate name should not be accepted 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Validator#62]
**Bug Description**
While Editing nickname already existing name is also accepted

**Steps to Reproduce**
1. Go to Validators
2. Click on three dots at top right corner
3. Edit nickname
4. Add already existing nickname

**Expected behavior**
While Editing nickname duplicate name should not be accepted 

**Actual behavior**
While Editing nickname already existing name is also accepted

**Screenshots/Recordings**
https://recordit.co/eOQt1G5Llh

**OS and Browser**
 - OS: [Windows 7]

**Additional context**
App version 1.0.0-alpha.21

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by shahraizali** [comment]
This is related to the account manager project. The Nickname is just on the frontend being stored in local storage. So that check is on frontend @buckyroberts can guide better. In my findings it was so I have fixed it locally should I create PR on the Account Manager repo? @buckyroberts

**Comment by angle943** [comment]
created the issue on the AccountManager repo: https://github.com/thenewboston-developers/Account-Manager/issues/400
