### ISSUE TITLE
OperationalError psycopg2 in connect

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Validator#76]
OperationalError psycopg2 in connect
could not connect to server: Connection refused Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432?

https://sentry.io/organizations/thenewboston/issues/2017035280/?project=5446923&query=is%3Aunresolved

**Comment by TheBrokenWasp** [comment]
Pretty sure this is the PostgreSQL not accepting the connections, right?
