### ISSUE TITLE
Validators API docs incomplete for Primary and Confirmation Validator

### ISSUE THREAD

**Issue by MathClassIsTough** [thenewboston-developers/Validator#79]
https://github.com/thenewboston-developers/Validator/blob/master/v1/validators/views/validator.py

currently has GET, PUT and POST but the API docs:
https://thenewboston.com/primary-validator-api/validators

currently only has documentation for GET; PUT and POST need to be documented for both the Primary Validator and the Confirmation Validator.

**Comment by buckyroberts** [comment]
Closing - included in these standardized documentation issues https://github.com/thenewboston-developers/Website/issues?q=is%3Aopen+is%3Aissue+label%3Adocumentation
