### ISSUE TITLE
Error in setup process

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Validator#88]
When I try to run pip3 install -r requirements/local.txt it errors out.

Collecting thenewboston==0.0.28 (from -r requirements/local.txt (line 92))
  Could not find a version that satisfies the requirement thenewboston==0.0.28 (from -r requirements/local.txt (line 92)) (from versions: 0.0.1, 0.0.3, 0.0.4, 0.0.5, 0.0.7, 0.0.8, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24)
No matching distribution found for thenewboston==0.0.28 (from -r requirements/local.txt (line 92))

**Comment by vosi** [comment]
What's your python version?

**Comment by mrbusysky** [comment]
3.6

**Comment by vosi** [comment]
ah ... ok, your package is listed with "Requires: Python >=3.7 " requirements
we need to upgrade the guide 
cc @buckyroberts
