### ISSUE TITLE
Fix Flake8 Issues for Validator

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Validator#91]
Fix all issues give when running `flake8 .` and then uncomment https://github.com/thenewboston-developers/Validator/blob/master/.github/workflows/pr.yml#L45

<img width="978" alt="Screen Shot 2020-11-21 at 2 41 45 PM" src="https://user-images.githubusercontent.com/8547538/99889217-d3847a80-2c07-11eb-8e05-c9c3788ca86e.png">

**Comment by AbhayAysola** [comment]
I'd like to try this, may I be assigned the issue.
